# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- loop_feature

pool:
  name: 'ITSBG3001'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.8
      publishJUnitResults: true
      testResultsFiles: '**/report/*.**'
      goals: 'clean test -Dsurefire.suiteXmlFiles=src/main/resources/scenarios/scenario.xml'
      
